set_ver_temp: &set_ver
  - |
      BASE_VER=$(shipctl get_resource_version_key base_ver versionName)
      CURR_VER=$(shipctl get_resource_version_key curr_ver versionName)

get_max_ver_temp: &get_max_ver
  - |
      B1="$(cut -d'.' -f1 <<< $BASE_VER )"
      B2="$(cut -d'.' -f2 <<< $BASE_VER )"
      B3="$(cut -d'.' -f3 <<< $BASE_VER )"
      C1="$(cut -d'.' -f1 <<< $CURR_VER )"
      C2="$(cut -d'.' -f2 <<< $CURR_VER )"
      C3="$(cut -d'.' -f3 <<< $CURR_VER )"

      if [ $B1 -gt $C1 ]; then
        HIGH_VER=$BASE_VER
      else
        if [ $C1 -gt $B1 ]; then
          HIGH_VER=$CURR_VER
        else
          if [ $B2 -gt $C2 ]; then
            HIGH_VER=$BASE_VER
          else
            if [ $C2 -gt $B2 ]; then
              HIGH_VER=$CURR_VER
            else
              if [ $B3 -gt $C3 ]; then
                HIGH_VER=$BASE_VER
              else
                HIGH_VER=$CURR_VER
              fi
            fi
          fi
        fi
      fi

# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:
  # adding JFrog artifactory integration so that credentials are available to CI Job
  # http://docs.shippable.com/platform/integration/jfrog-artifactoryKey/#jfrog-artifactory-integration
  hub:
    - integrationName: docker_repo
      type: dockerRegistryLogin

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
    - JFROG_ARTIFACTORY_IMG="node_app"
    - JFROG_ARTIFACTORY_REG=hendrix-docker-local.jfrog.io # {account name}

build:
  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    # npm mirrors can sometimes be flacky, better to use shippable_retry
    # http://docs.shippable.com/ci/advancedOptions/retry/
#    - shipctl retry "npm install"
    - npm install
    - mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
    - pushd $TESTS_LOC_DIR
    - $MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
    - $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" $SHIPPABLE_REPO_DIR/node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
    - $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR
    - popd

  # http://docs.shippable.com/ci/shippableyml/#post_ci
  post_ci:
    - BASE_VER=$(shipctl get_resource_version_key curr_ver versionName)
    - CURR_VER=$(shipctl get_resource_version_key node_app_img_jf versionName)
    - *get_max_ver
    - NEW_VERSION="$(shipctl bump_version $CURR_VER beta)"
    - docker build -t $JFROG_ARTIFACTORY_REG/$JFROG_ARTIFACTORY_IMG:$NEW_VERSION .
    - if [ "$IS_PULL_REQUEST" != true ]; then docker push $JFROG_ARTIFACTORY_REG/$JFROG_ARTIFACTORY_IMG:$NEW_VERSION; fi

  #this will be ignored if you are not using Assembly Lines to trigger another job after ci
  on_success:
    - shipctl put_resource_state node_app_img_jf versionName $NEW_VERSION

## OPTIONAL : In case you want to use this image in CD Assembly Lines
resources:
  - name: node_app_img_jf
    type: image
    integration: docker_repo # replace with your integration name
    versionTemplate:
      sourceName: "hendrix-docker-local.jfrog.io/node_app" # replace with your Hub URL
      versionName: latest

  - name: base_ver
    type: version
    versionTemplate:
      versionName: "0.0.0"

  - name: curr_ver
    type: version
    versionTemplate:
      versionName: "tbd"

jobs:
  - name: node_app_jfrog_runCI
    type: runCI
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: curr_ver
      - OUT: node_app_img_jf
    flags:
      - jfrog
      - docker

  - name: bump_minor
    type: runSh
    steps:
      - IN: base_ver
      - TASK:
          name: plus_minor
          script:
            - *set_ver
            - *get_max_ver
            - NEW_VERSION="$(shipctl bump_version $HIGH_VER minor)"
      - OUT: curr_ver
    on_success:
      script:
        - shipctl put_resource_state_multi "curr_ver" "versionName=$NEW_VERSION"

  - name: bump_patch
    type: runSh
    steps:
      - IN: base_ver
      - TASK:
          name: plus_minor
          script:
            - *set_ver
            - *get_max_ver
            - NEW_VERSION="$(shipctl bump_version $HIGH_VER patch)"
      - OUT: curr_ver
    on_success:
      script:
        - shipctl put_resource_state_multi "curr_ver" "versionName=$NEW_VERSION"

  - name: bump_major
    type: runSh
    steps:
      - IN: base_ver
      - TASK:
          name: plus_minor
          script:
            - *set_ver
            - *get_max_ver
            - NEW_VERSION="$(shipctl bump_version $HIGH_VER major)"
      - OUT: curr_ver
    on_success:
      script:
        - shipctl put_resource_state_multi "curr_ver" "versionName=$NEW_VERSION"